// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package money

import (
	"database/sql"
)

type Acc struct {
	ID       int64
	Name     string
	Xid      string
	Kind     string
	IsActive int64
}

type Cat struct {
	ID       int64
	Name     string
	Kind     string
	IsActive int64
}

type Plan struct {
	ID         int64
	StartDate  sql.NullString
	EndDate    sql.NullString
	CatID      int64
	AmountExpr string
	Period     string
}

type PlanPeriod struct {
	ID          int64
	PlanID      int64
	PeriodStart string
	PeriodEnd   string
	Amount      float64
}

type Rule struct {
	ID         int64
	StartDate  sql.NullString
	EndDate    sql.NullString
	TestExpr   string
	CatID      sql.NullInt64
	AmountExpr sql.NullString
	DescExpr   sql.NullString
	DateExpr   sql.NullString
	Ord        int64
}

type Tx struct {
	ID         int64
	Xid        string
	Date       string
	OrigDate   string
	Desc       string
	OrigDesc   string
	Amount     float64
	OrigAmount float64
	AccID      int64
	Ord        string
}

type TxCat struct {
	TxID  int64
	CatID int64
}
